name: fptr10_service
description: ATOL support for flutter
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^0.14.5
  freezed_annotation: ^0.14.3
  json_serializable: ^5.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:

flutter:
  plugin:
    platforms:
      android:
        package: company.dev.fptr10_service
        pluginClass: Fptr10ServicePlugin
