name: fptr10_service
description: unofficial ATOL plugin based on 10.9.4.0
version: 0.3.2
homepage: https://github.com/dev-company/fptr10_service

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.0
  json_serializable: ^6.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^2.0.0
  build_runner:

flutter:
  plugin:
    platforms:
      android:
        package: company.dev.fptr10_service
        pluginClass: Fptr10ServicePlugin
